#!/bin/bash

# @author Usb Key
# @mail usbkey9@gmail.com

./autoup $1


logPath="/var/log/uku.log";
cfgPath="./uku.cfg";
splPath="./sample.uku.cfg";
delimSub="-------------------------------------------------------------------------------";
delimTit="———————————————————————————————————————————————————————————————————————————————";

function fctExist() {
	if [[ $(type -t $1) == function ]]; then
		return 0;
	else
		return 1;
	fi
}

function execCmd() {
	local cmd=$1;

	if [[ ! $($cmd &>> /dev/null && echo 0) = 0 ]]; then
		return 1;
	else
		return 0;
	fi

}

function fatalError() {
	local red=$(tput setaf 1)
	local reset=$(tput sgr0)

	echo "${red}$1${reset}"
	if fctExist cleanTmp; then cleanTmp; fi
	exit;
}

function displayTitle() {
	local lenTitle=${#1};
	local lenDelim=${#delimTit};
	local lenTot=$((lenDelim / 2 - lenTitle / 2));

	echo $delimTit;
	for i in `seq 0 $lenTot`;
	do
		echo -ne " ";
	done
	echo $1;
	echo $delimTit;
}

function displaySubTitle() {
	echo $1;
	echo $delimSub;
}
