#!/bin/bash

# @author Mustafa Hasturk
# @mail mustafa.hasturk@yandex.com
# @author Caio Oliveira
# @mail caiooliveirafarias0@gmail.com
# @author Christoph Kepler
# @mail development@kepler.international
# @author Usb Key
# @mail usbkey9@gmail.com

cat << EOF
Ubuntu Kernel Upgrade - by Mustafa Hasturk
------------------------------------------
This script is based on the work of Mustafa Hasturk and was reworked by
Caio Oliveira and modified and fixed by Christoph Kepler

Current Development and Maintenance by Christoph Kepler

EOF

if [ -f ./ukupgrade ]; then
	SOURCE="${BASH_SOURCE[0]}"
	while [ -h "$SOURCE" ]; do
		DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
		SOURCE="$(readlink "$SOURCE")"
		[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
	done
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	cd $DIR
fi

script="$DIR/ukupgrade"

# Kernel URL
read -p "Do you want the Stable Release (if not sure, press y)? (y/n): " -n 1 -s rc
case "$rc" in
	y | Y) echo 'Stable Release'; kernelrc=0 ;;
	n | N) echo 'Release Candidate'; kernelrc=1 ;;
	*) echo 'Bad input. Aborting'; exit ;;
esac

read -p 'Do you want the generic kernel? (y/n): ' -n 1 -s km
case "$km" in
	y | Y) echo 'Generic'; kernelmode="generic" ;;
	*) echo 'LowLatency'; kernelmode="lowlatency" ;;
esac

read -p 'Do you want to autoremove old kernel? (y/n): ' -n 1 -s arm
case "$arm" in
	y | Y) echo 'Auto Remove'; arm=1 ;;
	*) echo 'Manual Remove'; arm=0 ;;
esac

sudo crontab -u root -l | grep -v $script | sudo crontab -u root -

read -p 'Do you want to update the kernel automatically? (y/n): ' -n 1 -s day
case "$day" in
	y | Y) echo 'Cronning'
		cron=1
		(sudo crontab -u root -l ; echo "0 */5 * * * $script >> /var/log/uku.log 2>&1") | sudo crontab -u root - ;;
	*) echo 'Deleting cron daily'
		cron=0 ;;
esac

if [ -f ./uku.cfg ]; then rm ./uku.cfg; fi

echo "kernelrc=$kernelrc" >> uku.cfg;
echo "kernelmode=$kernelmode" >> uku.cfg;
echo "arm=$arm" >> uku.cfg;
echo "cron=$cron" >> uku.cfg;

read -p 'Setup complete. Update the kernel right now? (y/n): ' -n 1 -s now
case "$now" in
	y | Y) echo 'Downloading'; ./ukupgrade ;;
esac

cat << EOF


Thanks for using this script! Hope it helped.
Give it a star: https://github.com/MarauderXtreme/uktools
EOF
