#!/bin/bash

# @author Usb Key
# @mail usbkey9@gmail.com

./autoup/autoup $1


logPath="/var/log/ukt.log";
cfgPath="./ukt.config";
splPath="./sample.config";
rotatePath="/etc/logrotate.d/ukt";
delimSub="-------------------------------------------------------------------------------";
delimTit="———————————————————————————————————————————————————————————————————————————————";

#You can only run one command at a time
function execCmd() {
	local cmd=$1;

	if [[ ! $($cmd &>> /dev/null && echo 0) = 0 ]]; then
		return 1;
	fi

	return 0;
}

# You can only run one command at a time
function execCmdAndDisplayErr() {
	local cmd=$1;

	if [[ ! $($cmd > /dev/null && echo 0) = 0 ]]; then
		return 1;
	fi

	return 0;
}

function fatalError() {
	local red=$(tput setaf 1)
	local reset=$(tput sgr0)

	echo "${red}$1${reset}"
	exit 2;
}

function displayTitle() {
	local lenTitle=${#1};
	local lenDelim=${#delimTit};
	local lenTot=$((lenDelim / 2 - lenTitle / 2));

	echo $delimTit;
	for i in `seq 0 $lenTot`;
	do
		echo -ne " ";
	done
	echo $1;
	echo $delimTit;
}

function displaySubTitle() {
	echo $1;
	echo $delimSub;
}

function notify() {
	if [[ -x "$(command -v notify-send)" ]]; then
		user=$(w -h | awk '{print $1}' | head -n 1)
		userId=$(id -u $user)

		params="DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$userId/bus";
		params="$params DISPLAY=:0.0"

		su $user -c "$params notify-send '$1' '$2' $3"
	fi
}

function waitDpkg() {
	while execCmd "sudo fuser /var/lib/dpkg/lock"; do
		sleep 0.5;
		echo "Waiting while dpkg is occupied";
	done
}

./migration