#!/bin/bash

# @author Mustafa Hasturk
# @mail mustafa.hasturk@yandex.com
# @author Caio Oliveira
# @mail caiooliveirafarias0@gmail.com
# @author Christoph Kepler
# @mail development@kepler.international
# @author Usb Key
# @mail usbkey9@gmail.com

SOURCE="${BASH_SOURCE[0]}"
while [[ -h "$SOURCE" ]]; do
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
cd "$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source ./common $$


script="$(pwd)/upgrade";
autoupFile="./autoup.on";
help="Usage: setup [OPTION]...
Create config file based on your chooses

  -unin,		Uninstall (delete cronjob)
";

function deleteCron() {
	sudo crontab -u root -l | grep -v "$logPath" | sudo crontab -u root -
}

if [[ "$1" = "-unin" ]]; then
	deleteCron;
	sudo rm -f $rotatePath $cfgPath;
	exit;
elif [[ "$1" = "-h" ]]; then
	echo "${help}";
	exit;
fi

displayTitle "UkTools Setup";
displaySubTitle "You can use this script as many time as you want";

PS3='Please enter your choice: '
options=("Release" "Testing" "Option 3" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Option 1") echo "you chose choice 1" ;;
        "Option 2") echo "you chose choice 2" ;;
        "Option 3") echo "you chose choice $REPLY which is $opt" ;;
        *)  echo "Bad input. Using default config";
			cp $splPath $cfgPath ;
			exit 2;;
    esac
done

#TODO test with cron
#TODO migration kernelrc -> kerneltype (sample + config)
read -p "Which kernel do you want ?" -n 1 -s kt
case "$kt" in
	y | Y)	echo "Testing kernel"; kerneltype="testing" ;;
	n | N)	echo "Release Candidate"; kerneltype=1 ;;
	*)
esac

read -p "Do you want the Generic kernel? (y/n): " -n 1 -s km
case "$km" in
	y | Y)	echo "Generic"; kernelmode="generic" ;;
	*)		echo "LowLatency"; kernelmode="lowlatency" ;;
esac

read -p "Do you want to autoremove old kernel? (y/n): " -n 1 -s arm
case "$arm" in
	y | Y)	echo "Auto Remove"; arm=1 ;;
	*)		echo "Manual Remove"; arm=0 ;;
esac

deleteCron;

read -p "Do you want to upgrade the kernel automatically? (y/n): " -n 1 -s day
case "$day" in
	y | Y)	echo "Cronning";
			cron=1;
			date="[\$(date '+\%Y-\%m-\%d \%H:\%M:\%S')]";
			(sudo crontab -u root -l ; echo "0 */2 * * * $script | while IFS= read -r line; do echo \"$date \$line\" ; done >> $logPath 2>&1") | sudo crontab -u root - ;;
	*)		echo "Deleting cron daily";
			cron=0 ;;
esac

read -p "Do you want to activate code auto update (if not sure, press y)? (y/n): " -n 1 -s aup
case "$aup" in
	y | Y)	echo "Enable"; touch $autoupFile ;;
	*)		echo "Disable"; if [[ -f $autoupFile ]]; then rm $autoupFile; fi ;;
esac

if [[ -f $cfgPath ]]; then rm $cfgPath; fi

echo "kerneltype=$kerneltype" >> $cfgPath;
echo "kernelmode=$kernelmode" >> $cfgPath;
echo "arm=$arm" >> $cfgPath;
echo "cron=$cron" >> $cfgPath;

echo "$logPath {
      monthly
      size 500M
      rotate 12
      compress
      delaycompress
      missingok
      notifempty
      create 644 root root
}" | sudo tee $rotatePath > /dev/null;

if [[ "$1" = "-noup" ]]; then exit; fi

read -p "Setup complete. Upgrade the kernel right now? (y/n): " -n 1 -s now
case "$now" in
	y | Y)	echo "Downloading"; sudo ./upgrade ;;
esac

echo
